import type { Metadata } from "next";
import "./globals.css";
import RealTimeNotificationManager from "../shared/components/common/notify/RealTimeNotificationManager";
import WebSocketInitializer from "../shared/lib/WebSocketInitializer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning={true}>
        {children}
        <RealTimeNotificationManager />
        <WebSocketInitializer />
      </body>
    </html>
  );
}
