[phases.setup]
nixPkgs = ["openjdk21"]

[phases.build]
dependsOn = ["setup"]
cmds = ["chmod +x gradlew", "./gradlew clean build -x test --no-daemon --refresh-dependencies"]

[start]
cmd = "java -Dspring.profiles.active=railway -jar build/libs/*.jar"
